export const REQUESTS_GOAL = [
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":1,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":29,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":13,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":26,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":20,"column":0,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":28,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"right"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":2,"column":2,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":2,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":2,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":2,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":2,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":9,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":17,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":18,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":6,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":6,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":6,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":6,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":9,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":17,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":18,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":13,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":13,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":13,"column":13,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":13,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":13,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":9,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":17,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":18,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":19,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":19,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":19,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":19,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":20,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":20,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":20,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":20,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":9,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":17,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":18,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":2,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":23,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":24,"column":2,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":24,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":24,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":24,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d"}',
    path: 'polyanets',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":2,"column":13,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":27,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":2,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":24,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":26,"column":26,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"up"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":4,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":9,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":19,"column":11,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"white"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":3,"column":27,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":16,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":25,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":15,"column":1,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":27,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":28,"column":20,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"left"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":8,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":11,"column":7,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":14,"column":17,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":21,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"blue"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":4,"column":8,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":23,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":10,"column":18,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":17,"column":14,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":6,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":19,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"purple"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":5,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":12,"column":28,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":16,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":27,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":26,"column":3,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":26,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","direction":"down"}',
    path: 'comeths',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":7,"column":15,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":9,"column":12,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":18,"column":22,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":21,"column":10,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":5,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
  {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body:
      '{"row":22,"column":24,"candidateId":"ad094505-8317-4754-bc3a-c5474ec4e34d","color":"red"}',
    path: 'soloons',
  },
];

export const phase2 = [
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RIGHT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'WHITE_SOLOON',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'BLUE_SOLOON',
    'POLYANET',
    'POLYANET',
    'PURPLE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RIGHT_COMETH',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'WHITE_SOLOON',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'BLUE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RED_SOLOON',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'PURPLE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'WHITE_SOLOON',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'BLUE_SOLOON',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'PURPLE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'RED_SOLOON',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'PURPLE_SOLOON',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'BLUE_SOLOON',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RIGHT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'WHITE_SOLOON',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'BLUE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'WHITE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RIGHT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'BLUE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'BLUE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'PURPLE_SOLOON',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'PURPLE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'RED_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'WHITE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'RIGHT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'RED_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'WHITE_SOLOON',
    'POLYANET',
    'POLYANET',
    'PURPLE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'RED_SOLOON',
    'POLYANET',
    'POLYANET',
    'BLUE_SOLOON',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'POLYANET',
    'RED_SOLOON',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'POLYANET',
    'POLYANET',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'DOWN_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'UP_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'RIGHT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'LEFT_COMETH',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
  [
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
    'SPACE',
  ],
];
